apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ejie-catalog-info
  description: Ejie catalogo info
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./domains/m001-domain.yaml
    - ./systems/d006-mensajeshlt7-system.yaml
