apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: cloud-ejie
  description: Everything related to Cloud Applications
  links:
    - url: http://example.com/domain/cloud-apps/
      title: Domain Readme
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: cloudops